stages:
  - quality
  - build

lint:
  stage: quality
  image: python:3.12
  script:
    - pip install flake8
    - flake8 .
  tags:
    - docker

build-and-push:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--tls=false"]
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    # Login sur Docker Hub
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    # Build de l'image docker (une seule fois)
    - docker build -t "$DOCKERHUB_USERNAME/plc-bot:latest" .
    # Push de l'image sur Docker Hub
    - docker push "$DOCKERHUB_USERNAME/plc-bot:latest"
  tags:
    - docker


